export const ActionType = {
  LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USER_LOGIN_FAILURE",
  LOGOUT: "USER_LOGOUT",
  REFRESH_REQUEST: "USER_REFRESH_TOKEN_REQUEST",
  REFRESH_SUCCESS: "USER_REFRESH_TOKEN_SUCCESS",
  REFRESH_FAILURE: "USER_REFRESH_TOKEN_FAILURE",
};
