
export interface INewReaderModel{
    Name: string,
    Sex: string,
    Card_No: string,
    Password: string,
    Birthday: Date,
    Expire_date: Date,
    Address: string,
    Tell: string,
    Email: string,
    Node: string,
    Avatar: string,
}
export interface IEditReaderModel{
    Id: string,
    Name: string,
    Sex: string,
    Card_No: string,
    Password: string,
    Birthday: Date,
    Expire_date: Date,
    Address: string,
    Tell: string,
    Email: string,
    Node: string,
    Avatar: string,
    Checkbox:boolean,
    MultipleSelect: string,
    Radio : string,
    TristateCheckbox: string,
    togglebutton :string
}
export interface IViewReaderModel{
    Id: string,
    Name: string,
    Sex: string,
    Card_No: string,
    Password: string,
    Birthday: Date,
    Expire_date: Date,
    Address: string,
    Tell: string,
    Email: string,
    Node: string,
    Avatar: string,
    Checkbox:boolean,
    MultipleSelect: string,
    Radio : string,
    TristateCheckbox: string,
    togglebutton :string
}
export interface IListReaderModel{
    Id: string,
    Name: string,
    Sex: string,
    Card_No: string,
    Password: string,
    Birthday: Date,
    Expire_date: Date,
    Address: string,
    Tell: string,
    Email: string,
    Node: string,
    Avatar: string,
}